definitions:
  response.APIResponse:
    properties:
      data:
        description: actual payload
      entity:
        description: e.g. "books"
        type: string
      message:
        description: e.g. "Success Get All Books"
        type: string
      state:
        description: e.g. "getAllBooks"
        type: string
      status:
        description: '"success" or "failed"'
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: ADF Code
    url: https://github.com/adf-code
  description: API service to manage books using Clean Architecture
  title: Beta Book API
  version: "1.0"
paths:
  /api/v1/payment-records/check/{id}:
    get:
      description: Retrieve a payment record entity using its UUID
      parameters:
      - description: UUID of the payment record
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "400":
          description: Invalid UUID
          schema:
            $ref: '#/definitions/response.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.APIResponse'
        "404":
          description: Book not found
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Check payment record by ID
      tags:
      - payment_records
  /books:
    get:
      consumes:
      - application/json
      description: List all books with filter, search, pagination
      parameters:
      - description: Search field (e.g., title)
        in: query
        name: search_field
        type: string
      - description: Search value (e.g., golang)
        in: query
        name: search_value
        type: string
      - collectionFormat: multi
        description: Filter field
        in: query
        items:
          type: string
        name: filter_field
        type: array
      - collectionFormat: multi
        description: Filter value
        in: query
        items:
          type: string
        name: filter_value
        type: array
      - collectionFormat: multi
        description: Range field
        in: query
        items:
          type: string
        name: range_field
        type: array
      - collectionFormat: multi
        description: Range lower bound
        in: query
        items:
          type: string
        name: from
        type: array
      - collectionFormat: multi
        description: Range upper bound
        in: query
        items:
          type: string
        name: to
        type: array
      - description: Sort field
        in: query
        name: sort_field
        type: string
      - description: Sort direction ASC/DESC
        in: query
        name: sort_direction
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Limit per page
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.APIResponse'
      security:
      - BearerAuth: []
      summary: Get list of books
      tags:
      - books
securityDefinitions:
  BearerAuth:
    description: 'Using token header using the Bearer scheme. Example: "Bearer {token}"'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
